[package]
name = "chumsky"
version = "0.5.0-alpha"
description = "A friendly parser combinator crate"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
repository = "https://github.com/zesterer/chumsky"
license = "MIT"
keywords = ["parser", "combinator", "token", "language", "syntax"]
categories = ["parsing", "text-processing"]
edition = "2018"
exclude = [
    "/misc/*",
	"/benches/*",
]

[dependencies]

[dev-dependencies]
ariadne = "0.1.2"
pom = "3.0"

[profile.bench]
debug = true
