[package]
name = "chumsky"
version = "0.7.0"
description = "A parser library for humans with powerful error recovery"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
repository = "https://github.com/zesterer/chumsky"
license = "MIT"
keywords = ["parser", "combinator", "token", "language", "syntax"]
categories = ["parsing", "text-processing"]
edition = "2018"
exclude = [
    "/misc/*",
	"/benches/*",
]

[features]
default = ["std"]
# Integrate with the standard library
std = []
# Enable nightly-only features like better compiler diagnostics
nightly = []

[dependencies]
# Due to https://github.com/rust-lang/cargo/issues/1839, this can't be optional
hashbrown = "0.11"

[dev-dependencies]
ariadne = "0.1.2"
pom = "3.0"
